### PR TITLE
Fix module controllers

### PR DESCRIPTION
**Pull request by ddpkts**
fixes module controllers
module version updated

### CODE REVIEW

**Comment by ddpkts** [comment]
If PR will be accepted please update tag to `1.0.2` also

**Comment by ddpkts** [comment]
@kermie It also would be nice to add Issue tab in this project, to fill other issues, there are some..

**Comment by pvanhemmen** [comment]
Any chance this PR will be merged someday? Thnx!

**Comment by keywan-ghadami-oxid** [comment]
Hi I can support on this project, in past I already maintained a fork for 5.x. Also I will ask some other developers to support. Any pull request and reviews are welcome.

**Pull request merged**
